'use client'

import dynamic from 'next/dynamic';
import { useEffect } from 'react'
import AOS from 'aos';
import 'aos/dist/aos.css';

const Header = dynamic(() => import('@/components/Header/Header'), { ssr: false });
const Policy = dynamic(() => import('@/components/Policy/Policy'), { ssr: false });
const Footer = dynamic(() => import('@/components/Footer/Footer'), { ssr: false });

export default function Home() {

  useEffect(() => {
    AOS.init({ duration: 900 });
  }, []);

  const title = (
    <>
      Terms of <span>services</span>
    </>
  )

  const text = (
    <>
    <div id="15-LIMITATION-OF-LIABILITY" class="text-rich-text w-richtext">
  <p>
    <strong class="text-color-primary">Trawler TERMS OF SERVICE <br />‍ </strong>
  </p>
  <p>Trawler, Inc. (“ <strong>Trawler</strong>”) provides a suite of fintech infrastructure services enabling end users to consolidate multiple financial data sets into a single standardized source for review and analysis (the “ <strong>Trawler Services</strong>”) through Trawler and third-party applications (collectively, the “ <strong>Applications</strong>”) and Trawler’s platform (the “ <strong>Trawler Platform</strong>”). These Trawler Terms of Service govern the access and use of Trawler Services, Applications, and Trawler Platform by a business customer (“ <strong>Customer</strong>”) who has executed an order for such products and services with Trawler (each, an “ <strong>Order</strong>”) to enable Customer to provide a service to its End Users (as defined below) with the products and services listed in the Order. Together, these Trawler Terms of Service and each Order is referred to as this “ <strong>Agreement</strong>.” By executing an Order, or by accessing or using the Trawler Services, Trawler Platform, or Applications, or by offering a service to End Users involving any such products and services, Customer irrevocably agrees to the terms and conditions of the Agreement. Trawler reserves the right to modify, add, or delete portions of these Trawler Terms of Service from time to time. If Trawler does so, it will post those changes to the current version of these Trawler Terms of Service and will use commercially reasonable efforts to notify Customer of such changes. If Customer objects to any such changes, it must notify Trawler in writing of its objection, and such changes will not be effective until Customer’s next renewal under its Order.&nbsp; </p>
  <ol id="1-definitions" role="list" class="text-color-primary">
    <li id="Definitions">
      <strong>DEFINITIONS. <br />‍ </strong>
    </li>
  </ol>
  <p>
    <strong></strong>Capitalized terms in this Agreement or an Order that are not defined when used have the meanings set forth in this <strong>Section 1</strong>.
  </p>
  <ol role="list">
    <li>“ <strong>Customer Systems</strong>” means Customer’s information technology infrastructure through which Customer provides its services and products to End Users, including any applications and APIs provided by Customer to End Users. </li>
    <li>&nbsp;“ <strong>Documentation</strong>” means text and/or graphical documentation related to the Trawler Services, the Applications or the Trawler Platform, in printed format, or otherwise that describes the features, functions and restrictions of the Trawler Services, the Applications or the Trawler Platform, which materials are designed to facilitate use of and which are made available by Trawler to Customer. </li>
    <li>&nbsp;“ <strong>End User Accounts</strong>” means the accounts and data sources where an end user’s financial account information and data is stored, including banking and credit card information, balance details, transaction information, and any other consumer financial data. </li>
    <li>“ <strong>End User Credentials</strong>” means the credentials that End Users use to access their End User Accounts. </li>
    <li>“ <strong>End User Data</strong>” means all account information and data that is collected, downloaded or otherwise received, directly or indirectly from an End User through the Trawler Services and/or the Applications, including (a) account name, account type and deposit addresses, (b) information related to account balances account transactions, in both amounts and in other currency equivalents (e.g. US Dollars), (c) information about account transactions, including amount, date, time, type, location, price, cost basis, fees, quantity, sender and recipient, (d) information about such End User as the account owner, such as publicly provided name, and (e) any other information or data received from an End User Account. </li>
    <li>“ <strong>End Users</strong>” means the individuals and entities to whom Customer provides services through the Applications, the Trawler Platform and the Customer Systems to access and use the Trawler Services.&nbsp; </li>
    <li>“ <strong>Intellectual Property Rights</strong>”&nbsp; means all (a) patents, patent disclosures and inventions (whether patentable or not), (b) trademarks, service marks, trade dress, trade names, logos, corporate names and domain names, together with all of the goodwill associated therewith, (c) copyrights and copyrightable works (including computer programs), and rights in data and databases, (d) trade secrets, know-how and other confidential information, and (e) all other intellectual property rights, in each case whether registered or unregistered and including all applications for, and renewals or extensions of, such rights, and all similar or equivalent rights or forms of protection in any part of the world.&nbsp; </li>
    <li>&nbsp;“ <strong>Losses</strong>” means all claims, demands, losses, injuries (including personal injury, sickness, or death), damages (including property damage), liabilities, deficiencies, actions, judgements, interest, awards, penalties, fines, costs or expenses of whatever kind, and other liabilities of any kind or nature, whether sounding in contract, tort, strict liability or otherwise, including reasonable attorneys’ fees and the cost of enforcing any right to indemnification hereunder and the cost of pursuing any insurance providers. </li>
    <li>“ <strong>Maintenance Release</strong>” means any update, upgrade, release or other adaptation or modification of the Trawler Services, the Applications and/or the Trawler Platform, including any updated Documentation, that Trawler may provide to Customer from time to time during the Term, which may contain, among other things, error corrections, enhancements, improvements or other changes to the user interface, functionality, compatibility, capabilities, performance, efficiency or quality of the Trawler Services, the Applications and/or the Trawler Platform. </li>
    <li>“ <strong>Order</strong>” means Trawler’s order form or other document executed by Trawler and Customer that specifies the Customer, the products and services to be provided by Trawler to Customer (including, without limitation, the specific Applications to be provided), the applicable fees and payments to be made by Customer, the term of the Order and any related subscriptions, and any other information related to the Trawler Services, the Applications, and the Trawler Platform.&nbsp; </li>
    <li>“ <strong>Privacy Policy</strong>” means Trawler’s privacy policy, which is currently located at https://www.trawler.io/policies/privacy-policy, as modified from time to time. </li>
    <li>“ <strong>Professional Services</strong>” means the implementation assistance, integration, training, consulting, or technical services provided by Trawler for Customer pursuant to an Order that specifies such services are being ordered by Customer. </li>
    <li>“ <strong>Representatives</strong>” means, with respect to a party, that party’s and its Affiliates’ employees, officers, directors, consultants, agents, contractors, and professional advisors. </li>
    <li>&nbsp;“ <strong>Third-Party Applications</strong>” means those Applications that are provided by an independent third-party. </li>
    <li>“ <strong>Third-Party Materials</strong>” means materials and information, in any form or medium, including any open source software, documents, data, content, specifications, or components of or relating to the Trawler Services, the Applications or the Trawler Platform and that are not proprietary to Trawler, including the Third-Party Applications. </li>
    <li>“ <strong>Third-Party Application Terms</strong>” means the additional terms and conditions, if any, that apply to the use of or access to a Third-Party Application.&nbsp; </li>
    <li>&nbsp; <strong>“Work Product</strong>” means all computer code, customizations, creations, inventions, reports, specifications, and documents that are first conceived, created or reduced to practice during the performance of Professional Services pursuant to this Agreement.&nbsp; <br />‍ </li>
  </ol>
  <ol id="2-Trawler-services" start="2" role="list" class="text-color-primary">
    <li>
      <strong>Trawler SERVICES. <br />‍ </strong>
    </li>
  </ol>
  <p>(a) Trawler Services. Subject to and conditioned on Customer’s compliance with the terms and conditions of this Agreement, Trawler shall use commercially reasonable efforts to provide to Customer access and use of the Trawler Services and the Applications specified in the Order during the Term.&nbsp;</p>
  <p>(b) Right to Use. Subject to the terms of this Agreement, Trawler grants to Customer a limited, non-exclusive, non-transferable, non-sublicensable, royalty-free and revocable right to access and use the Trawler Services to provide the Trawler Services to the End Users through the Applications and the Trawler Platform during the Term in accordance with the terms of this Agreement, the applicable Documentation.&nbsp;&nbsp;</p>
  <p>(d) White Label. Customer may white label the Trawler Services as incorporated into the Customer Systems. In such cases, Customer will include a prominent attribution such as “ <em>powered by Trawler</em>” or a similar phrase agreed upon by the parties. </p>
  <p>(e) Use Restrictions. Customer shall not, and agrees not to assist or otherwise permit or enable any third party to:</p>
  <ul role="list">
    <li>copy, modify, adapt, translate, create derivative works or improvements or merge copies of the Trawler Services, the Applications, the Trawler Platform, or the Documentation;</li>
    <li>translate, reverse engineer, de-compile or disassemble the Trawler Services, the Applications, or the Trawler Platform;</li>
    <li>use, disclose, or otherwise process any “personal information” (as that term is used in the Privacy Policy) other than in strict compliance with Customer’s terms and privacy policy and with all applicable law; provided that under no circumstances shall Customer sell any such personal information, provide it to any third party, or use it for marketing unless Customer has received the specific consent of each relevant End User;&nbsp;</li>
    <li>access or use, or permit the access or use of, the Trawler Services, the Applications, or the Trawler Platform, or access, transmit, process, or store End User Data, in violation of any applicable laws, statutes, rules, regulations or ordinances or in any manner that would be a breach of contract or agreement with the applicable End User;</li>
    <li>attempt to defeat, circumvent, or disable any copy protection mechanism or security or access limitation mechanism in the Trawler Services, the Applications, or the Trawler Platform;</li>
    <li>embed any open source, copyleft or community source code in any Trawler Services, Applications, Trawler Platform, or the Customer System, including, but not limited to, any libraries or code licensed under any General Public License, Lesser General Public License or similar license arrangement in any manner that would require disclosure or license of the Applications or the Trawler Platform in source code form, or for the purpose of making derivative works, or otherwise limit or restrict the consideration to be charged for the distribution of such software;</li>
    <li>interfere with or disrupt the integrity or performance of the Trawler Services, the Applications, or the Trawler Platform or any data contained in them;</li>
    <li>install, use, access, display and run the Trawler Services, the Applications or the Trawler Platform except in accordance with the terms of this Agreement;</li>
    <li>except as specifically permitted under the terms of this Agreement or to the extent that Customer has received the specific consent of each relevant End User, rent, lease, lend, sell, sublicense, assign, distribute, publish, transfer or otherwise make available the Trawler Services, the Applications, the Trawler Platform, or End User Data to any third party other than as permitted under this Agreement, including on or in connection with the internet or any time-sharing, service bureau, software as a service, cloud, or other technology or service;</li>
    <li>except as specifically provided under the terms of this Agreement, delete or in any manner alter the copyright, trademark, and other proprietary rights notices of Trawler appearing on the Trawler Services, the Applications, the Trawler Platform, or any other Trawler software or products;</li>
    <li>access or use the Trawler Services, the Applications, the Trawler Platform, or End User Data in any manner or for any purpose that infringes, misappropriates, or otherwise violates any intellectual property rights or other rights of any third party, or that violates any applicable law;some text <ul role="list">
        <li>use the Trawler Services, the Applications, the Trawler Platform, or the End User Data for purposes of: (i) benchmarking or competitive analysis of the Trawler Services, the Applications, or the Trawler Platform; (ii) developing, using, or providing a competing service, application, or platform; or (iii) any other purpose that is to Trawler’s detriment or commercial disadvantage;</li>
      </ul>
    </li>
  </ul>
  <ul role="list">
    <li>use the Trawler Services, the Applications, the Trawler Platform, or the End User Data in any manner or for any purpose or application not expressly permitted by this Agreement;</li>
    <li>sell or rent End User Data to marketers or any other third parties;</li>
    <li>collect and store any End User Credentials and/or End User Data other than as required to access or use any of the Trawler Services, the Applications, or the Trawler Platform, as authorized by the End User, as permitted by Trawler, and as permitted under applicable law;</li>
    <li>overload, flood, or spam any part of the Trawler Services, the Applications, or the Trawler Platform;</li>
    <li>create an account for any of the Trawler Services or Applications by any means other than Trawler’s publicly supported interfaces (e.g., creating developer accounts in an automated fashion or otherwise in bulk); or</li>
    <li>access or use any of the Trawler Services, the Applications, the Trawler Platform, or End User Data in a manner that violates any agreement between Customer and the End User or Trawler.</li>
  </ul>
  <p>(f) Third-Party Applications. Customer acknowledges and agrees that the Third-Party Applications are provided by independent third parties and that Trawler has no control over the Third-Party Applications, including with respect to Maintenance Releases, support, and any applicable Third-Party Application Terms. If an Order includes any Third-Party Applications, Customer must comply with all applicable Third-Party Application Terms.</p>
  <ol id="3-professional-services" start="3" role="list" class="text-color-primary">
    <li>
      <strong>PROFESSIONAL SERVICES. <br />‍ </strong>
    </li>
  </ol>
  <ol role="list">
    <li>Orders for Professional Services. Trawler will perform the Professional Services and deliver the Work Product as set forth in a fully executed Order that specifies Professional Services to be performed for the fees set forth in the Order. The Professional Services described in an Order are based on understandings and expectations that apply at the time such Order is prepared. Start and stop dates, if any, contained in such Order are not firm performance dates and may be revised during the term of any engagement, and they are to be regarded as estimated beginning and completion dates for the tasks and activities as of the date of such Order. Trawler will notify Customer promptly (via email or otherwise) if Trawler expects or encounters delays.</li>
    <li>Expenses.&nbsp; Customer will reimburse Trawler for reasonable and necessary out-of-pocket expenses (e.g., travel and living expenses) incurred by Trawler in conjunction with its performance of Professional Services. Trawler will use reasonable efforts to procure Customer’s prior approval to any such expenses. Unless included as a line item in an Order, such expenses are not included in the fees stated in the Order.</li>
    <li>On-Site Conduct.&nbsp; If performance of the Professional Services requires Trawler to be on-site at Customer’s premises, Trawler will ensure that while its personnel are on such premises, such personnel will obey all reasonable instructions, standards and procedures issued by Customer that are relevant to the presence of the Trawler personnel.</li>
    <li>Customer Obligations. Trawler will not be liable for any failure to perform Professional Services where such failure is the result of Customer’s or a third-party vendor&apos;s failure to perform its obligations or to otherwise provide reasonable cooperation in the provision of Professional Services. To facilitate Trawler’s performance of the Professional Services, Customer must: (i) promptly render or obtain all decisions and approvals so as not to delay or impede the performance of Professional Services; (ii) promptly provide or obtain all reasonable cooperation, assistance, information, data, facilities, equipment, and suitably configured computer products that are necessary for performance of Professional Services; (iii) notify Trawler of any issues, concerns or disputes with the Professional Services; and (iv) undertake any other responsibility referred to in an Order as being a matter of Customer responsibility.</li>
    <li>Change Orders. Either party may, from time to time, deem it necessary to make changes by altering, adding to or deducting from the Professional Services or Work Product described in an Order, including requests for changes in project plans, scope, specifications, schedule, designs or requirements.&nbsp; Any such request for a change must be in writing, and neither party will be bound by the changes until both parties’ authorized representatives have executed a written change order describing the changes.</li>
    <li>Customer-Provided Materials. Customer will provide all information, software, hardware, electronic media, artwork, designs, tools, equipment, devices, drawings, patterns, proofs, specifications, notes, memoranda, documents, or other material that must be provided by Customer in connection with Professional Services (“ <strong>Customer-Provided Materials</strong>”).&nbsp; As between Customer and Trawler, Customer owns all right, title, and interest in and to the Customer-Provided Materials. Customer represents and warrants that it has the necessary rights to provide the Customer-Provided Materials to Trawler for the purposes for which such materials are provided. Customer grants to Trawler a non-exclusive, non-transferable license and right to use, copy, and modify the Customer-Provided Materials as necessary and appropriate to perform the Professional Services. </li>
    <li>License to Work Product. The Work Product is not a work-made-for-hire, and Trawler retains all Intellectual Property Rights in and to the Work Product, subject only to the licenses granted to Customer pursuant to this Agreement and the applicable Order. Trawler grants Customer a limited, non-exclusive, non-transferable, non-sublicensable license and right to use the Work Product as necessary and appropriate in connection with Customer’s permitted use of the Trawler Services under this Agreement. Customer will not, and will not permit or encourage any affiliate or third party to:&nbsp; (i) use, distribute, license or sublicense the Work Product except in connection with Customer’s permitted use of the Trawler Service; (ii) modify, alter, reverse engineer, decompile, translate, disassemble, or otherwise attempt to derive or discover the source code of the Work Product, in whole or in part; (iii) write or develop any derivative software or any other software based on the Work Product; or (iv) remove or destroy any copyright, trademark or other proprietary markings or notices or confidentiality legends placed upon or contained within the Work Product or any copies of it. <br />‍ </li>
  </ol>
  <ol id="4-customer-obligations" start="4" role="list" class="text-color-primary">
    <li>
      <strong>CUSTOMER OBLIGATIONS</strong>. <br />‍
    </li>
  </ol>
  <p>(a) Customer Control and Responsibility. Customer has and will retain sole responsibility for: (i) all End User Data, including its use; (ii) the operation, maintenance and management of the Customer Systems and (iii) all access to and use of the Trawler Services, directly or indirectly by or through the Applications, the Trawler Platform or the Customer Systems.&nbsp;</p>
  <p>(b) Compliance with Laws. Customer shall comply with all applicable federal, state, local, and international laws related to Customer’s and its End Users’ access to and use of the Trawler Services, the Applications, and the End User Data, including all privacy and financial laws.</p>
  <p>(c) Consent; End User Agreements. Customer shall be solely responsible for obtaining express written consent from each End User authorizing Trawler to obtain their End User Data from their End User Accounts and provide it to Customer for use in connection with the Trawler Services. Access and use of the Trawler Services by the End Users requires that each End User have manifested assent to a written agreement between Customer and the End User that contains terms substantially similar to, and no less protective of Trawler, than the Trawler End User Terms of Service that Trawler requires of individual end-user customers of Trawler’s products and services, which are available at <a href="https://www.trawler.io/policies/terms-and-conditions">https://www.trawler.io/policies/terms-and-conditions</a>. Customer represents, warrants, and covenants that: (i) each End User has manifested its assent to an agreement with Customer that contains such terms, and (ii) Customer will enforce such agreements against End Users who breach them and will notify Trawler promptly of any such breach that relates to Trawler or the products and services provided under this Agreement. Upon request from Trawler, Customer will assign to Trawler any right of action against an End User that results from the End User’s breach (or alleged breach) of an End User agreement that relates to the Trawler Services. </p>
  <p>(d) Customer Systems. Customer acknowledges that Customer is solely responsible, and that Trawler has no responsibility or liability of any kind, for the content, development, operation, support or maintenance of the Customer Systems. Without limiting the foregoing, Customer is and will be solely responsible for creating and displaying information and content on, through or within the Customer Systems.&nbsp;</p>
  <p>(e) Customer Account Management. Customer is responsible for maintaining the confidentiality of its Customer account and any login information or other account authorization credentials relating to its account with Trawler. Customer is responsible and liable for all activities that occur under its Trawler account credentials. <strong>&nbsp;</strong>
  </p>
  <p>&nbsp;(f) Data Breaches. Customer shall promptly notify Trawler in writing in the event that Customer becomes aware of any material breach of its security safeguards or has reason to believe that any End User Data in Customer’s possession, custody, or control may have been subject to unauthorized disclosure, access, or use (but no later than twenty-four (24) hours after becoming aware), which notification shall include the following information to the extent known at the time and updated as Customer learns more: (i) the nature of the unauthorized disclosure or use; (ii) End User Data or other Confidential Information that was disclosed or used; (iii) the identity of the persons or entities who received the unauthorized disclosure or made the unauthorized use; (iv) what corrective action Customer took or will take to prevent further unauthorized disclosures or uses; (v) what Customer did or will do to mitigate any adverse effect of such unauthorized disclosure or use; and (vi) such other information as Trawler may reasonably request. <br />‍ </p>
  <ol id="5-intellectual-property-rights" start="5" role="list" class="text-color-primary">
    <li>
      <strong>INTELLECTUAL PROPERTY RIGHTS. <br />‍ </strong>
    </li>
  </ol>
  <p>(a) Trawler Services. All right, title and interest in and to the Trawler Services, the Applications, the Trawler Platform, and the Documentation, including all Intellectual Property Rights in each of them, are and will be owned by Trawler and the respective rights holders in the Third-Party Materials. Customer has no right, license, or authorization with respect to the Trawler Services, the Applications, the Trawler Platform, or the Documentation (including Third-Party Materials) except as expressly set forth in this Agreement and subject to the restrictions and other terms of this Agreement. All other rights in and to the Trawler Services, the Applications, the Trawler Platform, and the Documentation (including Third-Party Materials) are expressly reserved by Trawler and the respective third-party licensors.</p>
  <p>(b) Feedback. Customer hereby grants to Trawler a non-exclusive, worldwide, fully paid-up, royalty-fee, non-terminable, perpetual, irrevocable right and license to use, disclose, modify, reproduce, license, distribute, commercialize and otherwise freely exploit any feedback, comments, or suggestions that Customer provides with respect to the Trawler Services, the Applications and/or the Trawler Platform and all related Intellectual Property Rights, without restriction of any kind and without any right of accounting. <br />‍ </p>
  <ol id="6-end-user-data" start="6" role="list" class="text-color-primary">
    <li>
      <strong>END USER DATA. <br />‍ </strong>
    </li>
  </ol>
  <p>(a) Permitted Use. The parties acknowledge and agree that each End User owns all right, title and interest in and to its End User Accounts and End User Data, subject to the rights and licenses described in this Agreement. When Trawler accesses End User Data from End User Accounts to provide that data to the End User via the Trawler Services and Customer Systems, Trawler hereby grants to Customer the limited, nonexclusive, nontransferable right and license during the Term to use, display, and reproduce that End User Data solely to provide the Trawler Services and the Applications, on behalf of, and at the direction of, the End Users. &nbsp;&nbsp;</p>
  <p>(b) End User Benefit. Customer acknowledges and agrees that its access to and use of the End User Data is solely for the benefit of the End Users who own that data. Any information or works derived from the End User Data will be used solely for the benefit of the respective End Users. Customer shall not use the End User Data for any other purpose, except to the extent that it has received the specific consent of each relevant End User for each such other purpose.&nbsp;&nbsp;</p>
  <p>(c) End User Data Obtained from End User Accounts. Customer acknowledges that the Trawler Services and the Applications require interactions with the End User Accounts. &nbsp;Trawler makes no representations or warranties as to the availability of such End User Accounts, which may be required to be used for Trawler to deliver the Trawler Services. Such End User Accounts may require certain requirements and criteria to be met prior to End User Data being made available to Trawler, Customer, and End Users, including information security and privacy requirements. To the extent Trawler’s ability to obtain End User Data from any End User Account or make available such End User Data to Customer is conditioned upon Customer meeting such requirements or criteria, Customer shall not be entitled to receive, and Trawler shall not be required to provide, such End User Data until Customer has met such requirements and criteria to the satisfaction of Trawler and the applicable End User Account provider. Trawler makes no representation, warranty or guarantee regarding the consistency or quality of any End User Data. <br />‍ </p>
  <p>(d) Security Obligations. Trawler and Customer shall each follow industry best practices with respect to access and use of End User Data, including the following:</p>
  <ul role="list">
    <li>maintaining administrative, technical, and physical safeguards that are designed to ensure the security, privacy, and confidentiality of End User Data;</li>
    <li>using best industry practice encryption when storing or transmitting any End User Data;</li>
    <li>maintaining reasonable access controls to ensure that only authorized individuals that have a business need have access to any End User Data;</li>
    <li>monitoring their respective systems for any unauthorized access and patching vulnerabilities in a timely fashion;</li>
    <li>planning for and responding to security incidents;</li>
    <li>storing all End User Data securely and in accordance with all applicable laws; and</li>
    <li>taking all reasonable and appropriate steps (at each party’s own expense) to protect all End User Data in the event of a failure of security safeguards or unauthorized access to any End User Data from or through such party, including the provision of the appropriate or legally required notices to affected persons and government or regulatory agencies (as applicable).</li>
  </ul>
  <ol role="list">
    <li>(e) Privacy Policy. These Terms of Service incorporate the Privacy Policy. By executing an Order or using any of the Trawler Services, Customer agrees to the Privacy Policy. <br />‍ </li>
  </ol>
  <ol id="7-fees-and-payments" start="7" role="list" class="text-color-primary">
    <li>
      <strong>FEES AND PAYMENTS.</strong>
    </li>
  </ol>
  <p>(a) Payment Terms. Customer will pay Trawler the fees set forth in each Order without setoff, deduction, or counterclaim. Payments are due in U.S. dollars, and except as otherwise specified in an Order, all payments under this Agreement are due within 30 days of Customer’s receipt of invoice. All fees are in U.S. dollars, and unless otherwise agreed by the parties, all payments must be made by ACH transfer. Trawler will provide payment instructions. Except as expressly set forth in these Terms of Service, all payments are nonrefundable. Fees stated in any Order are exclusive of any federal, state, municipal, value-added or other taxes or governmental charges applicable to the transactions contemplated by such Order. Customer will pay any such applicable taxes or charges invoiced by Trawler or, if Customer is required to withhold any such amounts, Customer will increase the amount paid to Trawler to ensure that Trawler receives, net of any such taxes or charges, the amount specified in the Order (except that Customer has no responsibility for any taxes based on Trawler’s income).</p>
  <p>(b) Fees. The fees payable by Customer under an Order may include some or all of the following:</p>
  <p>(i) Trawler Services Subscription Fees. The fees for the right to access and use the Trawler Services are referred to as the “ <strong>Subscription Fees</strong>.” Payment of the Subscription Fee entitles Customer to access the Trawler Services by the number of End Users specified in the Order for the period specified in the Order, and also entitles Customer to receive the support and maintenance described in Section 9 of these Terms of Service. If Customer exceeds the number of End Users for which Customer has previously paid a Subscription Fee, Trawler will invoice and Customer will pay an incremental Subscription Fee for the additional End Users for the remainder of the then-current billing period.&nbsp; </p>
  <p>(ii) Third-Party Application Fees. The fees for the right to access and use the Third-Party Applications specified in the Order are referred to as the “ <strong>Third-Party Application Fees</strong>.” Payment of the Third-Party Application Fees entitles Customer to the Third-Party Application(s) specified in the Order based on the time periods and other metrics term specified in the Order.&nbsp; </p>
  <p>(iv) Other Fees. Other fees (for example, fees for Professional Services), if any, will be as described in the applicable Order. <br />‍ </p>
  <ol id="8-representation-and-warranties" start="8" role="list">
    <li>
      <strong class="text-color-primary">REPRESENTATIONS AND WARRANTIES.</strong>
      <br />Each party represents and warrants to the other party that: (i) it is duly organized, validly existing and in good standing as a corporation or other entity under the laws of the jurisdiction of its incorporation or other organization; (ii) it has the full right, power and authority to enter into and perform its obligations and grant the rights, licenses, consents and authorizations it grants or is required to grant under this Agreement; (iii) the execution of this Agreement by its representative whose signature is set forth at the end of this Agreement has been duly authorized by all necessary corporate or organizational action of such party; and (iv) when executed and delivered by both parties, this Agreement will constitute the legal, valid and binding obligation of such party, enforceable against such party in accordance with its terms. <br />‍
    </li>
  </ol>
  <ol id="9-support-and-maintenance" start="9" role="list">
    <li>
      <strong class="text-color-primary">SUPPORT AND MAINTENANCE</strong>. <br />Trawler shall provide technical and other support with respect to the Trawler Services during Trawler’s normal business hours (generally weekdays from 9:00am to 5:00pm CT, excluding holidays). Customer may contact Trawler for technical support via email at suppport@Trawler.io or as otherwise directed by Trawler. Trawler shall also provide Customer with all Maintenance Releases (including updated Documentation) that Trawler may, in its sole discretion, make generally available to its customers at no additional charge. All Maintenance Releases, on being provided by Trawler to Customer hereunder, are deemed to be a part of the Trawler Services, the Applications and/or the Trawler Platform, subject to the terms and conditions in this Agreement. <br />‍
    </li>
    <li id="10-confidecial-information" class="text-color-primary">
      <strong>CONFIDENTIAL INFORMATION</strong>.
    </li>
  </ol>
  <p>(a) Confidential Information. In connection with this Agreement, each party (as the “ <strong>Disclosing Party</strong>”) may disclose or make available to the other party (as the “ <strong>Receiving Party</strong>”) Confidential Information. Subject to <strong>Section 10(b)</strong>, “ <strong>Confidential Information</strong>” means information in any form or medium (whether oral, written, electronic or other) that: (i) if disclosed in writing or other tangible form or medium, is marked “confidential” or “proprietary”;&nbsp; (ii) if disclosed orally or in other intangible form or medium, is identified by the Disclosing Party or its Representative as confidential or proprietary when disclosed; or (iii) due to the nature of its subject matter or the circumstances surrounding its disclosure, would reasonably be understood to be confidential or proprietary. <strong>&nbsp;</strong>
  </p>
  <p>(b) Exclusions. Confidential Information does not include information that the Receiving Party can demonstrate by written or other documentary records: (i) was rightfully known to the Receiving Party without restriction on use or disclosure prior to such information’s being disclosed or made available to the Receiving Party in connection with this Agreement; (ii) was or becomes generally known by the public other than by the Receiving Party’s or any of its Representatives’ noncompliance with this Agreement; (iii) is received by the Receiving Party on a non-confidential basis from a third party that is not, at the time of such receipt, under any obligation to maintain its confidentiality; or (iv) is independently developed by the Receiving Party without reference to or use of any Confidential Information.</p>
  <p>(c) Protection of Confidential Information. As a condition to being provided with any disclosure of or access to Confidential Information, the Receiving Party shall during and after the Term:&nbsp;</p>
  <ol role="list">
    <li>not access or use Confidential Information other than as necessary to exercise its rights or perform its obligations under and in accordance with this Agreement;&nbsp;</li>
    <li>except as may be permitted under the terms and conditions of <strong>Section (d)</strong>, not disclose or permit access to Confidential Information other than to its Representatives who: (A) need to know such Confidential Information for purposes of the Receiving Party’s exercise of its rights or performance of its obligations under and in accordance with this Agreement; (B) have been informed of the confidential nature of the Confidential Information and the Receiving Party’s obligations under this <strong>Section </strong>; and (C) are bound by written confidentiality and restricted use obligations at least as protective of the Confidential Information as the terms set forth in this <strong>Section </strong>; </li>
    <li>safeguard the Confidential Information from unauthorized use, access or disclosure using at least the degree of care it uses to protect its most sensitive information and in no event less than a reasonable degree of care; and</li>
    <li>promptly notify the Disclosing Party of any unauthorized use or disclosure of Confidential Information and take all reasonable steps to prevent further unauthorized use or disclosure; and&nbsp;</li>
    <li>ensure its Representatives’ compliance with, and be responsible and liable for, any of its Representatives’ non-compliance with, the terms of this <strong>Section .</strong>
    </li>
  </ol>
  <p>Notwithstanding any other provisions of this Agreement, the Receiving Party’s obligations under this <strong>Section&nbsp; </strong>with respect to any Confidential Information that constitutes a trade secret or personal or financial data under any applicable law will continue until such time, if ever, as such Confidential Information ceases to qualify for protection under one or more such applicable laws other than as a result of any act or omission of the Receiving Party or any of its Representatives. </p>
  <p>(d) Compelled Disclosures. The Receiving Party may disclose the Disclosing Party’s Confidential Information pursuant to a valid order issued by a court or government agency or as otherwise required by law, provided that (i) the Receiving Party provides the Disclosing Party with prior written notice of such obligation and the opportunity to oppose such disclosure or obtain a protective order; (ii) the Receiving Party only discloses such Confidential Information as is required to comply with such order or law (as advised by competent counsel); and (iii) no such disclosure shall otherwise exempt such Confidential Information from being treated as confidential under this <strong>Section </strong>. </p>
  <ol id="11-terms-and-determination" start="11" role="list" class="text-color-primary">
    <li>
      <strong>TERM AND TERMINATION.</strong>
    </li>
  </ol>
  <p>(a) Term; Subscription Renewals. This Agreement is effective on the date that the parties have fully executed an Order (or such other effective date as specified in the Order) and shall continue for as long as there is an Order being performed by the parties (the “ <strong>Term</strong>”). The products and services provided under this Agreement are provided on a subscription basis. Unless otherwise specified in an Order, there is an initial subscription period for the services ordered that is set forth in the Order (the “ <strong>Initial Subscription Term</strong>”), and that subscription period automatically renews for additional 12-month periods (each a “ <strong>Renewal Subscription Term</strong>”) unless either party provides written notice of nonrenewal at least 60 days prior to renewal. The fees for any Renewal Subscription Term are Trawler’s then-current standard subscription fees at the time of renewal unless otherwise agreed in writing by the parties. </p>
  <p>(b) Termination. This Agreement may be terminated only for cause as follows:</p>
  <p>(i) by Trawler, if Customer breaches a payment obligation under this Agreement and such breach remains uncured ten (10) days after Trawler provides Customer with written notice of such breach; or</p>
  <p>(ii) by either party, if such other party breaches any non-payment obligation or term under this Agreement and such breach: (A) is incapable of cure, in which case such termination is effective upon written notice; or (B) is capable of cure, but remains uncured thirty (30) days after the non-breaching party provides the breaching party with written notice of such breach, in which case such termination is effective at the end of such 30-day period; or</p>
  <p>&nbsp;(iii) by either party, effective immediately upon written notice, if the other party: (A) is dissolved or liquidated or takes any corporate action for such purpose; (B) becomes insolvent or is generally unable to pay its debts as they become due; (C) becomes the subject of any voluntary or involuntary bankruptcy proceeding under any domestic or foreign bankruptcy or insolvency law; (D) makes or seeks to make a general assignment for the benefit of its creditors; or (E) applies for, or consents to, the appointment of a trustee, receiver or custodian for a substantial part of its property.</p>
  <p>(c) Effect of Termination. On the expiration or termination of this Agreement for any reason:</p>
  <ol role="list">
    <li>all rights, licenses, and authorizations granted to Customer under this Agreement will immediately terminate, and Customer shall:some text <ol role="list">
        <li>immediately cease all use of and other activities with respect to the Trawler Services, the Applications, the Trawler Platform, and Documentation;</li>
        <li>within fifteen (15) days, deliver to Trawler, or at Trawler’s written request destroy, and permanently erase from all devices and systems Customer directly or indirectly controls, the Documentation and Trawler’s Confidential Information, including all documents, files and tangible materials (and any partial and complete copies) containing, reflecting, incorporating or based on any of the foregoing, whether or not modified or merged into other materials; and</li>
        <li>certify to Trawler in a written instrument signed by an executive officer that it has complied with the requirements of this <strong>Section (c)(i)</strong>. </li>
      </ol>
    </li>
    <li>Customer shall pay all amounts due to Trawler of any kind under this Agreement no later than ten (10) days after the effective date of the termination of this Agreement under <strong>Section (b)</strong>.&nbsp; </li>
    <li>Trawler shall: (A) within fifteen (15) days, deliver to Customer, or at Customer’s written request destroy, and permanently erase from all devices and systems Trawler directly or indirectly controls, Customer’s Confidential Information, including all documents, files and tangible materials (and any partial and complete copies) containing, reflecting, incorporating or based on Customer’s Confidential Information, whether or not modified or merged into other materials and (b) certify to Customer in a written instrument signed by an executive officer that it has complied with the requirements of this <strong>Section (c)(iii)</strong>. </li>
  </ol>
  <p>(d) Survival. In addition to those Sections of these Terms of Service and each Order which by their nature are intended to survive any expiration or termination of this Agreement, <strong>Sections 1, (e), 2(f), 4(f), 5, 10, 11(c) and (d), 12, 13, 15, 16, 17</strong> and <strong>18</strong> of these Terms of Service shall specifically survive any expiration or termination of this Agreement.&nbsp; </p>
  <ol id="12-indeminification" start="12" role="list" class="text-color-primary">
    <li>
      <strong>INDEMNIFICATION.</strong>
    </li>
  </ol>
  <p>(a) Trawler shall hold harmless, defend and indemnify Customer and its affiliates and their respective officers, directors, employees and agents from and against any and all Losses, brought by or resulting from claims by third parties which are based on or arising out of any actual or alleged (i) negligence or willful misconduct of, or breach of the terms of this Agreement by, Trawler or any of its Representatives, (ii) violation of any applicable law by Trawler or any of its Representatives; or (iii) infringement of any third party’s US Intellectual Property Rights (an “ <strong>Infringement Claim</strong>”) as a result of using the Trawler Services, the Applications (excluding any Third-Party Application) or the Trawler Platform in accordance with this Agreement. However, Trawler has no obligation under this Section 12(a) to the extent that any Infringement Claim arises out of or results from: </p>
  <p>(A) any combination of the Trawler Services, the Applications and/or the Trawler Platform with any hardware, system or other software not provided or authorized in writing by Trawler, if such infringement would not have occurred but for such combination;</p>
  <p>(B) any modification of the Trawler Services, the Applications and/or the Trawler Platform not provided or authorized in writing by Trawler, or Customer’s negligence, abuse, misapplication, or misuse of the Trawler Services, the Applications and/or the Trawler Platform, if such infringement would not have occurred but for such modification, neglect, abuse, misapplication or misuse; or</p>
  <p>(C) any breach by Customer of the terms and conditions of this Agreement.</p>
  <p>In addition, if an Infringement Claim is made by a third party against Customer or if Trawler believes that a likelihood of such an Infringement Claim exists, Trawler, in a reasonable exercise of its discretion, shall either procure for Customer the right to continue using the affected Trawler Services, Applications and/or Trawler Platform, modify them to make them non-infringing while still able to meet their functionality, or replace them with non-infringing services or applications of like functionality. If none of the foregoing is reasonably available to Trawler, Trawler may terminate this Agreement, in which case Customer shall immediately cease use of the Trawler Services, the Applications and/or the Trawler Platform in accordance with Section 11(c) and Trawler shall refund to Customer a pro-rata portion of the fees that were pre-paid in connection with the remainder of the then-current Initial Subscription Term or Renewal Subscription Term, as applicable. &nbsp;</p>
  <p>(b) Customer shall hold harmless, defend and indemnify Trawler and its affiliates and their respective officers, directors, employees and agents from and against any and all Losses brought by or resulting from claims by third parties which are based on or arising out of any actual or alleged: (i) negligence or willful misconduct of, or breach of this Agreement (including, without limitation, breach of any applicable Third-Party Application Terms) by Customer or any of its Representatives or End Users, (ii) violation of any applicable law by Customer or any of its Representatives, or (iii) the use of the Trawler Services, the Applications and/or the Trawler Platform in violation of this Agreement. <br />‍ </p>
  <ol start="13" role="list">
    <li>
      <strong id="13-limitation-of-warranties" class="text-color-primary">LIMITATION OF WARRANTIES. <br />‍ </strong>EXCEPT AS SET FORTH IN THIS AGREEMENT, THE Trawler SERVICES, THE APPLICATIONS, THE QUILT PLATFORM, THE DOCUMENTATION AND ANY OTHER PRODUCTS, INFORMATION, MATERIALS AND SERVICES PROVIDED BY Trawler ARE PROVIDED “AS IS” AND WITH ALL FAULTS, AND Trawler HEREBY DISCLAIMS ALL OTHER WARRANTIES, WHETHER EXPRESS, IMPLIED, STATUTORY OR OTHER (INCLUDING ALL WARRANTIES ARISING FROM COURSE OF DEALING, USAGE OR TRADE PRACTICE) AND SPECIFICALLY DISCLAIMS ALL IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. WITHOUT LIMITING THE FOREGOING, AND EXCEPT AS SET FORTH IN THIS AGREEMENT, Trawler MAKES NO WARRANTY OF ANY KIND THAT THE Trawler SERVICES, APPLICATIONS OR QUILT PLATFORM, OR ANY OTHER PRODUCTS, INFORMATION, MATERIALS AND SERVICES OR THE RESULTS OF THE USE OF ANY OF THEM, WILL MEET CUSTOMER’S OR ANY OTHER PERSON’S REQUIREMENTS, OPERATE WITHOUT INTERRUPTION, ACHIEVE ANY INTENDED RESULT, BE COMPATIBLE OR WORK WITH ANY OTHER SYSTEM, GOODS, MATERIALS OR SERVICES.&nbsp; <br />‍
    </li>
    <li>
      <strong id="14-insurance" class="text-color-primary">INSURANCE. <br />
      </strong>Each party shall purchase and maintain in force during the Term, insurance with coverage and in amounts as may be required in accordance with good industry practices as reasonably determined by such party. <br />‍
    </li>
    <li>
      <strong class="text-color-primary">LIMITATION OF LIABILITY.</strong>
    </li>
  </ol>
  <p>(a) EXCEPT FOR A PARTY’S GROSS NEGLIGENCE OR WILLFUL MISCONDUCT, OR A BREACH OF <strong>SECTIONS 2(e), 4, 6, </strong>OR <strong>10</strong>, OR WITH RESPECT TO ANY OBLIGATION UNDER <strong>SECTION 12</strong>, IN NO EVENT SHALL EITHER PARTY BE LIABLE TO THE OTHER PARTY OR ANY OTHER ENTITY FOR LOST PROFITS, LOST BUSINESS OPPORTUNITIES, OR COSTS OF PROCUREMENT OF SUBSTITUTE GOODS BY ANYONE OR FOR ANY INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER FOR BREACH OF WARRANTY, BREACH OF CONTRACT, REPUDIATION OF CONTRACT, NEGLIGENCE OR OTHERWISE, AND WHETHER OR NOT SUCH PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, AND NOTWITHSTANDING THE FAILURE OF ITS ESSENTIAL PURPOSE. </p>
  <p> (b) EXCEPT FOR Trawler’S GROSS NEGLIGENCE OR WILLFUL MISCONDUCT, A BREACH OF <strong>SECTION 10</strong>, OR Trawler’S OBLIGATIONS UNDER <strong>SECTION 12, </strong>IN NO EVENT WILL THE AGGREGATE LIABILITY OF Trawler, ITS LICENSORS, SERVICE PROVIDERS AND SUPPLIERS ARISING OUT OF OR RELATED TO THIS AGREEMENT, THE Trawler SERVICES, APPLICATIONS, OR THE QUILT PLATFORM, WHETHER ARISING UNDER OR RELATED TO BREACH OF CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY OR ANY OTHER LEGAL OR EQUITABLE THEORY, EXCEED THE FEES ACTUALLY PAID TO Trawler UNDER THE APPLICABLE ORDER FOR THE TWELVE (12) MONTH PERIOD PRECEDING THE EVENT GIVING RISE TO THE RELATED CLAIM. THE FOREGOING LIMITATIONS APPLY NOTWITHSTANDING ANY FAILURE OF ITS ESSENTIAL PURPOSE. </p>
  <ol start="16" role="list">
    <li>
      <strong id="16-ASSIGNMENT" class="text-color-primary">ASSIGNMENT.</strong>
      <br />Neither party may assign or delegate all or any part of this Agreement without the express written consent of the other party, except that a party may freely assign this Agreement in connection with a merger, acquisition or sale of all or substantially all or substantially all of its assets; provided that (a) the assigning party promptly notifies the other party of any such assignment and (b) the assignee agrees in writing to assume all of the assigning party’s obligations under this Agreement. Any unauthorized attempt to transfer this Agreement, in whole or in part, is void. Subject to the foregoing, this Agreement will be binding upon the parties and their heirs, executors, personal representatives, successors and assigns, and will inure to the benefit of the other party and their respective successors and assigns. <br />‍
    </li>
    <li>&nbsp; <strong id="17-GOVERNING-LAW" class="text-color-primary">GOVERNING LAW AND DISPUTE RESOLUTION. <br />‍ </strong>This Agreement will be governed by and construed in accordance with the substantive laws of the State of Texas without regard to its conflict of law principles. Any legal suit, action or proceeding arising out of or related to this Agreement, the Trawler Services, the Applications, the Trawler Platform, and/or the transactions contemplated by this Agreement (a “Dispute”) will be instituted exclusively in the federal or state courts located in Dallas County, Texas, and each party irrevocably submits to the exclusive venue and personal jurisdiction of such courts in any such Dispute. Service of process, summons, notice or other document by mail to such party’s address set forth herein will be effective service of process for any suit, action or other proceeding brought in any such court. EACH PARTY IRREVOCABLY AND UNCONDITIONALLY WAIVES ANY RIGHT IT MAY HAVE TO A TRIAL BY JURY IN RESPECT OF ANY DISPUTE. In the event that any Dispute is instituted or commenced by either party against the other, the prevailing party shall be entitled to recover from the non-prevailing party its actual out-of-pocket fees and expenses incurred, including fees for attorneys, expert witnesses, accountants, and court costs. <br />‍ </li>
    <li class="text-color-primary">&nbsp; <strong id="18-miscellaneous">MISCELLANEOUS.</strong>
    </li>
  </ol>
  <p>(a) Further Assurances. Upon a party’s reasonable request, the other party shall, at the requesting party’s sole cost and expense, execute and deliver all such documents and instruments, and take all such further actions, necessary to give full effect to this Agreement.</p>
  <p>(b) Relationship of the Parties. The relationship between the parties is that of independent contractors. Nothing contained in this Agreement shall be construed as creating any agency, partnership, joint venture or other form of joint enterprise, employment or fiduciary relationship between the parties, and neither party shall have authority to contract for or bind the other party in any manner whatsoever.</p>
  <p>(c) Public Announcements. Except as otherwise provided in this <strong>Section 18(c)</strong>, neither party shall issue or release any announcement, statement, press release or other publicity or marketing materials relating to this Agreement or otherwise use the other party’s trademarks, service marks, trade names, logos, domain names or other indicia of source, affiliation or sponsorship, in each case, without the prior written consent of the other party. Notwithstanding the foregoing, Trawler may include Customer’s name and logo in its lists of current or former customers in promotional and marketing materials.&nbsp;&nbsp; </p>
  <p>(d) Notices. All notices, requests, consents, claims, demands, waivers and other communications under this Agreement relating to the parties’ rights and remedies shall be in writing and shall be deemed to have been given (i) when delivered by hand (with written confirmation of receipt); (ii) when received by the addressee if sent by a nationally recognized overnight courier (receipt requested); (iii) on the date sent by email (with confirmation of transmission) if sent during normal business hours of the recipient, and on the next business day if sent after normal business hours of the recipient, (iv) on the fifth (5 <sup>th</sup>) business day after the date mailed by certified or registered mail, return receipt requested, postage prepaid. Notices to Trawler must be sent to the address indicated below. Notices to Customer must be sent to the address provided in the Order. Either party may update its address or information for notices by providing written notice in accordance with this <strong>Section 18(d)</strong>. <br />‍ </p>
  <p>Notices to Trawler:</p>
  <p>Trawler, Inc.</p>
  <p>169 Madison Ave, #2132</p>
  <p>New York, NY 10016</p>
  <p>Email: support@Trawler.com</p>
  <p>Attention: COO <br />‍ </p>
  <p> (e) Entire Agreement; Conflicts.&nbsp; This Agreement, including these Terms of Services together with the Orders and any Third-Party Application Terms, constitute the sole and entire agreement of the parties with respect to the subject matter of this Agreement and supersedes all prior and contemporaneous understandings, agreements, representations and warranties, both written and oral, with respect to such subject matter. If there is any conflict between these Terms of Service, Third-Party Application Terms, and the terms of any Order: (i) the Third-Party Application Terms control and govern with respect to the applicable Third-Party Application, and (ii) the terms of an Order control over any conflicting terms of these Terms of Service to the extent such Order expresses an intent to override provisions in these Terms of Service.</p>
  <p>(f) No Third-party Beneficiaries. Except as may be specified in Third-Party Application Terms, if applicable, this Agreement is for the sole benefit of the parties hereto and their respective permitted successors and permitted assigns and nothing else in this Agreement is intended to or shall confer upon any other party any legal or equitable right, benefit or remedy of any nature whatsoever under or by reason of this Agreement.</p>
  <p>(g) Amendment and Modification; Waiver. No amendment to or modification of any part of this Agreement is effective unless it is in writing and signed by an authorized representative of each party. No waiver by any party of any of the provisions of this Agreement shall be effective unless explicitly set forth in writing and signed by the party so waiving. Except as otherwise set forth in this Agreement, no failure to exercise, or delay in exercising, any rights, remedy, power or privilege arising from this Agreement shall operate or be construed as a waiver; nor shall any single or partial exercise of any right, remedy, power or privilege hereunder preclude any other or further exercise thereof or the exercise of any other right, remedy, power or privilege.</p>
  <p>(h) Severability.&nbsp; If any provision of this Agreement is invalid, illegal, or unenforceable in any jurisdiction, such invalidity, illegality, or unenforceability shall not affect any other term or provision of this Agreement or invalidate or render unenforceable such term or provision in any other jurisdiction. Upon such determination that any term or other provision is invalid, illegal, or unenforceable, the parties shall negotiate in good faith to modify this Agreement so as to effect the original intent of the parties as closely as possible in a mutually acceptable manner in order that the transactions contemplated hereby be consummated as originally contemplated to the greatest extent possible.</p>
  <p>(i) Force Majeure.&nbsp; The obligations of a party (other than payment) will be suspended by the occurrence of any event beyond its reasonable control and not caused by its negligence that renders its performance impossible including acts of God, war, fire, flood, accident, strike, casualty, power failures, governmental acts, orders, or restrictions, or inability to obtain suitable and sufficient labor and materials.&nbsp; The party invoking force majeure shall (i) send written notice of the event to the other within a reasonable time after the invoking party knew or should have known that performance would be delayed or prevented due to the force majeure and (ii) take reasonable steps to limit the duration and effect of any such force majeure.&nbsp;&nbsp;</p>
  <p>(j) Equitable Relief.&nbsp; Each party acknowledges and agrees that a breach or threatened breach by such party of any of its obligations under this Agreement relating to the other party’s Intellectual Property Rights or Confidential Information would cause the other party irreparable harm for which monetary damages would not be an adequate remedy and agrees that, in the event of such breach or threatened breach, the other party will be entitled to seek equitable relief, including a restraining order, an injunction, specific performance, and any other relief that may be available from any court, without any requirement to post a bond or other security, or to prove actual damages or that monetary damages are not an adequate remedy. Such remedies are not exclusive and are in addition to all other remedies that may be available at law, in equity or otherwise.</p>
  <p>(k) Export Controls. Customer shall not import, export, re-export, or transfer, directly or indirectly, any part of the Trawler Services, the Applications, or the Trawler Platform or any underlying intellectual Property Rights, information, or technology except with Trawler’s prior written approval and in full compliance with all United States, foreign, and other applicable export control laws and regulations.</p>
  <p>(l) Counterparts.&nbsp; An Order may be executed in counterparts, each of which is deemed an original, but all of which together are deemed to be one and the same agreement. A signed copy of an Order delivered by e-mail or other means of electronic transmission is deemed to have the same legal effect as delivery of an original signed copy of an Order.</p>
</div>
    </>
  )


  return (

    <>
      <Header />
      <Policy title={title} text={text} />
      <Footer />
    </>
  );
}
